// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "utils": {
      name: "utils",
      description: "",
      type: "registry:lib",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/lib/utils.ts",
        type: "registry:lib",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "sliding-text-demo": {
      name: "sliding-text-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/sliding-text-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/sliding-text-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "popping-text-demo": {
      name: "popping-text-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/popping-text-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/popping-text-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "glitch-text-demo": {
      name: "glitch-text-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/glitch-text-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/glitch-text-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "typing-text-demo": {
      name: "typing-text-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/typing-text-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/typing-text-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "card-flip-demo": {
      name: "card-flip-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/card-flip-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/card-flip-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "floating-card-demo": {
      name: "floating-card-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/floating-card-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/floating-card-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "toast-card-demo": {
      name: "toast-card-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/toast-card-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/toast-card-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "linear-waveform-demo": {
      name: "linear-waveform-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/linear-waveform-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/linear-waveform-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "bar-waveform-demo": {
      name: "bar-waveform-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/bar-waveform-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/bar-waveform-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "bar-loader-demo": {
      name: "bar-loader-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/bar-loader-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/bar-loader-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "circular-loader-demo": {
      name: "circular-loader-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/circular-loader-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/circular-loader-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "circular-waveform-demo": {
      name: "circular-waveform-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/circular-waveform-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/circular-waveform-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "screen-loader-demo": {
      name: "screen-loader-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/screen-loader-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/screen-loader-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "bar-waveform": {
      name: "bar-waveform",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/components/bar-waveform.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/bar-waveform.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "circular-waveform": {
      name: "circular-waveform",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/components/circular-waveform.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/circular-waveform.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "linear-waveform": {
      name: "linear-waveform",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/components/linear-waveform.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/linear-waveform.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "card-flip": {
      name: "card-flip",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/components/card-flip.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/card-flip.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "floating-card": {
      name: "floating-card",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/components/floating-card.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/floating-card.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "toast-card": {
      name: "toast-card",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/components/toast-card.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/toast-card.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "bar-loader": {
      name: "bar-loader",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/components/bar-loader.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/bar-loader.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "circular-loader": {
      name: "circular-loader",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/components/circular-loader.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/circular-loader.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "screen-loader": {
      name: "screen-loader",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/components/screen-loader.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/screen-loader.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "glitch-text": {
      name: "glitch-text",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/components/glitch-text.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/glitch-text.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "popping-text": {
      name: "popping-text",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/components/popping-text.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/popping-text.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "sliding-text": {
      name: "sliding-text",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/components/sliding-text.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/sliding-text.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "typing-text": {
      name: "typing-text",
      description: "",
      type: "registry:component",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/components/typing-text.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/components/typing-text.tsx")),
      source: "",
      category: "",
      subcategory: "",
      meta: undefined,
      chunks: []
    },
    "u-bar-waveform": {
      name: "u-bar-waveform",
      description: "",
      type: "registry:block",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/blocks/bar-waveform/page.tsx",
        type: "registry:page",
        target: "app/main.tsx"
      },{
        path: "registry/default/components/bar-waveform.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/blocks/bar-waveform/page.tsx")),
      source: "__registry__/default/blocks/bar-waveform/page.tsx",
      category: "",
      subcategory: "",
      meta: {"iframeHeight":"600px","container":"w-full bg-surface min-h-svh flex px-6 py-12 items-center md:pt-20 justify-center min-w-0 xl:py-24","mobile":"component"},
      chunks: []
    },
    "u-circular-waveform": {
      name: "u-circular-waveform",
      description: "",
      type: "registry:block",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/blocks/circular-waveform/page.tsx",
        type: "registry:page",
        target: "app/main.tsx"
      },{
        path: "registry/default/components/circular-waveform.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/blocks/circular-waveform/page.tsx")),
      source: "__registry__/default/blocks/circular-waveform/page.tsx",
      category: "",
      subcategory: "",
      meta: {"iframeHeight":"600px","container":"w-full bg-surface min-h-svh flex px-6 py-12 items-center md:pt-20 justify-center min-w-0 xl:py-24","mobile":"component"},
      chunks: []
    },
    "u-linear-waveform": {
      name: "u-linear-waveform",
      description: "",
      type: "registry:block",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/blocks/linear-waveform/page.tsx",
        type: "registry:page",
        target: "app/main.tsx"
      },{
        path: "registry/default/components/linear-waveform.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/blocks/linear-waveform/page.tsx")),
      source: "__registry__/default/blocks/linear-waveform/page.tsx",
      category: "",
      subcategory: "",
      meta: {"iframeHeight":"600px","container":"w-full bg-surface min-h-svh flex px-6 py-12 items-center md:pt-20 justify-center min-w-0 xl:py-24","mobile":"component"},
      chunks: []
    },
    "u-card-flip": {
      name: "u-card-flip",
      description: "",
      type: "registry:block",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/blocks/card-flip/page.tsx",
        type: "registry:page",
        target: "app/main.tsx"
      },{
        path: "registry/default/components/card-flip.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/blocks/card-flip/page.tsx")),
      source: "__registry__/default/blocks/card-flip/page.tsx",
      category: "",
      subcategory: "",
      meta: {"iframeHeight":"600px","container":"w-full bg-surface min-h-svh flex px-6 py-12 items-center md:pt-20 justify-center min-w-0 xl:py-24","mobile":"component"},
      chunks: []
    },
    "u-floating-card": {
      name: "u-floating-card",
      description: "",
      type: "registry:block",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/blocks/floating-card/page.tsx",
        type: "registry:page",
        target: "app/main.tsx"
      },{
        path: "registry/default/components/floating-card.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/blocks/floating-card/page.tsx")),
      source: "__registry__/default/blocks/floating-card/page.tsx",
      category: "",
      subcategory: "",
      meta: {"iframeHeight":"600px","container":"w-full bg-surface min-h-svh flex px-6 py-12 items-center md:pt-20 justify-center min-w-0 xl:py-24","mobile":"component"},
      chunks: []
    },
    "u-toast-card": {
      name: "u-toast-card",
      description: "",
      type: "registry:block",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/blocks/toast-card/page.tsx",
        type: "registry:page",
        target: "app/main.tsx"
      },{
        path: "registry/default/components/toast-card.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/blocks/toast-card/page.tsx")),
      source: "__registry__/default/blocks/toast-card/page.tsx",
      category: "",
      subcategory: "",
      meta: {"iframeHeight":"600px","container":"w-full bg-surface min-h-svh flex px-6 py-12 items-center md:pt-20 justify-center min-w-0 xl:py-24","mobile":"component"},
      chunks: []
    },
    "u-bar-loader": {
      name: "u-bar-loader",
      description: "",
      type: "registry:block",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/blocks/bar-loader/page.tsx",
        type: "registry:page",
        target: "app/main.tsx"
      },{
        path: "registry/default/components/bar-loader.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/blocks/bar-loader/page.tsx")),
      source: "__registry__/default/blocks/bar-loader/page.tsx",
      category: "",
      subcategory: "",
      meta: {"iframeHeight":"600px","container":"w-full bg-surface min-h-svh flex px-6 py-12 items-center md:pt-20 justify-center min-w-0 xl:py-24","mobile":"component"},
      chunks: []
    },
    "u-circular-loader": {
      name: "u-circular-loader",
      description: "",
      type: "registry:block",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/blocks/circular-loader/page.tsx",
        type: "registry:page",
        target: "app/main.tsx"
      },{
        path: "registry/default/components/circular-loader.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/blocks/circular-loader/page.tsx")),
      source: "__registry__/default/blocks/circular-loader/page.tsx",
      category: "",
      subcategory: "",
      meta: {"iframeHeight":"600px","container":"w-full bg-surface min-h-svh flex px-6 py-12 items-center md:pt-20 justify-center min-w-0 xl:py-24","mobile":"component"},
      chunks: []
    },
    "u-screen-loader": {
      name: "u-screen-loader",
      description: "",
      type: "registry:block",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/blocks/screen-loader/page.tsx",
        type: "registry:page",
        target: "app/main.tsx"
      },{
        path: "registry/default/components/screen-loader.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/blocks/screen-loader/page.tsx")),
      source: "__registry__/default/blocks/screen-loader/page.tsx",
      category: "",
      subcategory: "",
      meta: {"iframeHeight":"600px","container":"w-full bg-surface min-h-svh flex px-6 py-12 items-center md:pt-20 justify-center min-w-0 xl:py-24","mobile":"component"},
      chunks: []
    },
    "u-glitch-text": {
      name: "u-glitch-text",
      description: "",
      type: "registry:block",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/blocks/glitch-text/page.tsx",
        type: "registry:page",
        target: "app/main.tsx"
      },{
        path: "registry/default/components/glitch-text.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/blocks/glitch-text/page.tsx")),
      source: "__registry__/default/blocks/glitch-text/page.tsx",
      category: "",
      subcategory: "",
      meta: {"iframeHeight":"600px","container":"w-full bg-surface min-h-svh flex px-6 py-12 items-center md:pt-20 justify-center min-w-0 xl:py-24","mobile":"component"},
      chunks: []
    },
    "u-popping-text": {
      name: "u-popping-text",
      description: "",
      type: "registry:block",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/blocks/popping-text/page.tsx",
        type: "registry:page",
        target: "app/main.tsx"
      },{
        path: "registry/default/components/popping-text.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/blocks/popping-text/page.tsx")),
      source: "__registry__/default/blocks/popping-text/page.tsx",
      category: "",
      subcategory: "",
      meta: {"iframeHeight":"600px","container":"w-full bg-surface min-h-svh flex px-6 py-12 items-center md:pt-20 justify-center min-w-0 xl:py-24","mobile":"component"},
      chunks: []
    },
    "u-sliding-text": {
      name: "u-sliding-text",
      description: "",
      type: "registry:block",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/blocks/sliding-text/page.tsx",
        type: "registry:page",
        target: "app/main.tsx"
      },{
        path: "registry/default/components/sliding-text.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/blocks/sliding-text/page.tsx")),
      source: "__registry__/default/blocks/sliding-text/page.tsx",
      category: "",
      subcategory: "",
      meta: {"iframeHeight":"600px","container":"w-full bg-surface min-h-svh flex px-6 py-12 items-center md:pt-20 justify-center min-w-0 xl:py-24","mobile":"component"},
      chunks: []
    },
    "u-typing-text": {
      name: "u-typing-text",
      description: "",
      type: "registry:block",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/blocks/typing-text/page.tsx",
        type: "registry:page",
        target: "app/main.tsx"
      },{
        path: "registry/default/components/typing-text.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/blocks/typing-text/page.tsx")),
      source: "__registry__/default/blocks/typing-text/page.tsx",
      category: "",
      subcategory: "",
      meta: {"iframeHeight":"600px","container":"w-full bg-surface min-h-svh flex px-6 py-12 items-center md:pt-20 justify-center min-w-0 xl:py-24","mobile":"component"},
      chunks: []
    },
  },
}
