// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "button": {
      name: "button",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/button.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/button.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "dialog": {
      name: "dialog",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/dialog.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/dialog.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "input": {
      name: "input",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/input.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/input.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "kbd": {
      name: "kbd",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/kbd.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/kbd.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "number-input": {
      name: "number-input",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/number-input.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/number-input.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "dropdown-menu": {
      name: "dropdown-menu",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/dropdown-menu.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/dropdown-menu.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "accordion": {
      name: "accordion",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/accordion.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/accordion.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "checkbox": {
      name: "checkbox",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/checkbox.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/checkbox.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "tabs": {
      name: "tabs",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/tabs.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/tabs.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "avatar": {
      name: "avatar",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/avatar.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/avatar.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "tooltip": {
      name: "tooltip",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/tooltip.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/tooltip.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "select": {
      name: "select",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/select.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/select.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "toggle": {
      name: "toggle",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/toggle.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/toggle.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "popover": {
      name: "popover",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/popover.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/popover.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "separator": {
      name: "separator",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/separator.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/separator.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "toolbar": {
      name: "toolbar",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/toolbar.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/toolbar.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "alert-dialog": {
      name: "alert-dialog",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/alert-dialog.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/alert-dialog.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "checkbox-group": {
      name: "checkbox-group",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/checkbox-group.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/checkbox-group.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "preview-card": {
      name: "preview-card",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/preview-card.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/preview-card.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "progress": {
      name: "progress",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/progress.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/progress.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "radio-group": {
      name: "radio-group",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/radio-group.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/radio-group.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "collapsible": {
      name: "collapsible",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/collapsible.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/collapsible.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "scroll-area": {
      name: "scroll-area",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/scroll-area.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/scroll-area.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "slider": {
      name: "slider",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/slider.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/slider.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "label": {
      name: "label",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/label.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/label.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "switch": {
      name: "switch",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/switch.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/switch.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "toggle-group": {
      name: "toggle-group",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/toggle-group.tsx",
        type: "registry:ui",
        target: ""
      },{
        path: "registry/default/ui/toggle.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/toggle-group.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "card": {
      name: "card",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/card.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/card.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "badge": {
      name: "badge",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/badge.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/badge.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "skeleton": {
      name: "skeleton",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/skeleton.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/skeleton.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "meter": {
      name: "meter",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/meter.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/meter.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "toast": {
      name: "toast",
      description: "",
      type: "registry:ui",
      registryDependencies: ["https://clippkit.com/r/button"],
      files: [{
        path: "registry/default/ui/toast.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/toast.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "textarea": {
      name: "textarea",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/textarea.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/textarea.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "utils": {
      name: "utils",
      description: "",
      type: "registry:lib",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/lib/utils.ts",
        type: "registry:lib",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "button-demo": {
      name: "button-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/button-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/button-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "button-destructive": {
      name: "button-destructive",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/button-destructive.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/button-destructive.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "button-ghost": {
      name: "button-ghost",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/button-ghost.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/button-ghost.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "button-icon": {
      name: "button-icon",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/button-icon.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/button-icon.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "button-link": {
      name: "button-link",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/button-link.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/button-link.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "button-loading": {
      name: "button-loading",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/button-loading.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/button-loading.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "button-outline": {
      name: "button-outline",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/button-outline.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/button-outline.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "button-secondary": {
      name: "button-secondary",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/button-secondary.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/button-secondary.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "dialog-custom-close-button": {
      name: "dialog-custom-close-button",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/dialog-custom-close-button.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/dialog-custom-close-button.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "dialog-with-no-x-button": {
      name: "dialog-with-no-x-button",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/dialog-with-no-x-button.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/dialog-with-no-x-button.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "dialog-nested": {
      name: "dialog-nested",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/dialog-nested.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/dialog-nested.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "input-demo": {
      name: "input-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/input-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/input-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "input-with-label": {
      name: "input-with-label",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/input-with-label.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/input-with-label.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "input-with-floating-label": {
      name: "input-with-floating-label",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/input-with-floating-label.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/input-with-floating-label.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "input-disabled": {
      name: "input-disabled",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/input-disabled.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/input-disabled.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "kbd-demo": {
      name: "kbd-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/kbd-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/kbd-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "kbd-outline": {
      name: "kbd-outline",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/kbd-outline.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/kbd-outline.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "kbd-ghost": {
      name: "kbd-ghost",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/kbd-ghost.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/kbd-ghost.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "number-input-demo": {
      name: "number-input-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/number-input-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/number-input-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "number-input-min-max": {
      name: "number-input-min-max",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/number-input-min-max.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/number-input-min-max.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "number-input-disabled": {
      name: "number-input-disabled",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/number-input-disabled.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/number-input-disabled.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "number-input-scrub-direction": {
      name: "number-input-scrub-direction",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/number-input-scrub-direction.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/number-input-scrub-direction.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "dropdown-menu-demo": {
      name: "dropdown-menu-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/dropdown-menu-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/dropdown-menu-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "dropdown-menu-radio": {
      name: "dropdown-menu-radio",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/dropdown-menu-radio.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/dropdown-menu-radio.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "dropdown-menu-checkbox": {
      name: "dropdown-menu-checkbox",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/dropdown-menu-checkbox.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/dropdown-menu-checkbox.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "dropdown-menu-hover": {
      name: "dropdown-menu-hover",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/dropdown-menu-hover.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/dropdown-menu-hover.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "accordion-demo": {
      name: "accordion-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/accordion-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/accordion-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "accordion-demo-two": {
      name: "accordion-demo-two",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/accordion-demo-two.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/accordion-demo-two.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "accordion-disabled": {
      name: "accordion-disabled",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/accordion-disabled.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/accordion-disabled.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "accordion-multiple": {
      name: "accordion-multiple",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/accordion-multiple.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/accordion-multiple.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "checkbox-demo": {
      name: "checkbox-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/checkbox-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/checkbox-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "checkbox-disabled": {
      name: "checkbox-disabled",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/checkbox-disabled.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/checkbox-disabled.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "tabs-demo": {
      name: "tabs-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/tabs-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/tabs-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "avatar-demo": {
      name: "avatar-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/avatar-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/avatar-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "select-demo": {
      name: "select-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/select-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/select-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "select-with-group": {
      name: "select-with-group",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/select-with-group.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/select-with-group.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "select-align-trigger": {
      name: "select-align-trigger",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/select-align-trigger.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/select-align-trigger.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "tooltip-demo": {
      name: "tooltip-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/tooltip-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/tooltip-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "toggle-demo": {
      name: "toggle-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/toggle-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/toggle-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "toggle-outline": {
      name: "toggle-outline",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/toggle-outline.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/toggle-outline.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "toggle-disabled": {
      name: "toggle-disabled",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/toggle-disabled.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/toggle-disabled.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "toggle-large": {
      name: "toggle-large",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/toggle-large.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/toggle-large.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "toggle-small": {
      name: "toggle-small",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/toggle-small.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/toggle-small.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "popover-demo": {
      name: "popover-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/popover-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/popover-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "popover-hover": {
      name: "popover-hover",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/popover-hover.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/popover-hover.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "separator-demo": {
      name: "separator-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/separator-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/separator-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "separator-vertical": {
      name: "separator-vertical",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/separator-vertical.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/separator-vertical.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "toolbar-demo": {
      name: "toolbar-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/toolbar-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/toolbar-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "toolbar-with-input": {
      name: "toolbar-with-input",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/toolbar-with-input.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/toolbar-with-input.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "alert-dialog-demo": {
      name: "alert-dialog-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/alert-dialog-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/alert-dialog-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "alert-dialog-confirmation": {
      name: "alert-dialog-confirmation",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/alert-dialog-confirmation.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/alert-dialog-confirmation.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "checkbox-group-demo": {
      name: "checkbox-group-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/checkbox-group-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/checkbox-group-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "checkbox-group-parent": {
      name: "checkbox-group-parent",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/checkbox-group-parent.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/checkbox-group-parent.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "checkbox-group-nested-parent": {
      name: "checkbox-group-nested-parent",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/checkbox-group-nested-parent.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/checkbox-group-nested-parent.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "preview-card-demo": {
      name: "preview-card-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/preview-card-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/preview-card-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "progress-demo": {
      name: "progress-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/progress-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/progress-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "progress-with-label": {
      name: "progress-with-label",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/progress-with-label.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/progress-with-label.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "progress-with-value": {
      name: "progress-with-value",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/progress-with-value.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/progress-with-value.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "radio-group-demo": {
      name: "radio-group-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/radio-group-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/radio-group-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "radio-group-disabled": {
      name: "radio-group-disabled",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/radio-group-disabled.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/radio-group-disabled.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "collapsible-demo": {
      name: "collapsible-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/collapsible-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/collapsible-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "scroll-area-demo": {
      name: "scroll-area-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/scroll-area-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/scroll-area-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "scroll-area-horizontal": {
      name: "scroll-area-horizontal",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/scroll-area-horizontal.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/scroll-area-horizontal.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "slider-demo": {
      name: "slider-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/slider-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/slider-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "slider-disabled": {
      name: "slider-disabled",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/slider-disabled.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/slider-disabled.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "slider-with-value": {
      name: "slider-with-value",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/slider-with-value.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/slider-with-value.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "slider-vertical": {
      name: "slider-vertical",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/slider-vertical.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/slider-vertical.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "switch-demo": {
      name: "switch-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/switch-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/switch-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "switch-disabled": {
      name: "switch-disabled",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/switch-disabled.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/switch-disabled.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "switch-square": {
      name: "switch-square",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/switch-square.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/switch-square.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "switch-large": {
      name: "switch-large",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/switch-large.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/switch-large.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "switch-small": {
      name: "switch-small",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/switch-small.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/switch-small.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "label-demo": {
      name: "label-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/label-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/label-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "toggle-group-demo": {
      name: "toggle-group-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/toggle-group-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/toggle-group-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "toggle-group-disabled": {
      name: "toggle-group-disabled",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/toggle-group-disabled.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/toggle-group-disabled.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "toggle-group-large": {
      name: "toggle-group-large",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/toggle-group-large.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/toggle-group-large.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "toggle-group-multiple": {
      name: "toggle-group-multiple",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/toggle-group-multiple.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/toggle-group-multiple.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "toggle-group-outline": {
      name: "toggle-group-outline",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/toggle-group-outline.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/toggle-group-outline.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "toggle-group-small": {
      name: "toggle-group-small",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/toggle-group-small.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/toggle-group-small.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "card-demo": {
      name: "card-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/card-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/card-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "card-demo-1": {
      name: "card-demo-1",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/card-demo-1.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/card-demo-1.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "badge-demo": {
      name: "badge-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/badge-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/badge-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "badge-secondary": {
      name: "badge-secondary",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/badge-secondary.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/badge-secondary.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "badge-outline": {
      name: "badge-outline",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/badge-outline.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/badge-outline.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "badge-destructive": {
      name: "badge-destructive",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/badge-destructive.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/badge-destructive.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "skeleton-demo": {
      name: "skeleton-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/skeleton-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/skeleton-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "skeleton-shimmer": {
      name: "skeleton-shimmer",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/skeleton-shimmer.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/skeleton-shimmer.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "skeleton-gradient": {
      name: "skeleton-gradient",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/skeleton-gradient.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/skeleton-gradient.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "meter-demo": {
      name: "meter-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/meter-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/meter-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "toast-demo": {
      name: "toast-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/toast-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/toast-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "toast-with-action": {
      name: "toast-with-action",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/toast-with-action.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/toast-with-action.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "toast-promise": {
      name: "toast-promise",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/toast-promise.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/toast-promise.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "textarea-demo": {
      name: "textarea-demo",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/textarea-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/textarea-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "mode-toggle": {
      name: "mode-toggle",
      description: "",
      type: "registry:example",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/examples/mode-toggle.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/examples/mode-toggle.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
  },
}
